---
# Ansible Playbook to upgrade Cisco IOS 

- name: Upgrade CISCO IOS for C9300 switches
  hosts: C9300

  vars: 
    upgrade_ios_version: 16.09.07

  tasks:
    - name: CHECK CURRENT VERSION
      ios_facts:

    - debug: 
        msg: 
        - "Current version is {{ ansible_net_version }}"

    - debug: 
        msg: 
        - "Image is compliant and will not be upgraded"

      when: ansible_net_version == upgrade_ios_version

    - debug: 
        msg: 
        - "Image is not compliant and will be upgraded"
        - "Upgrade to IOS release 16.09.07"

      when: ansible_net_version != upgrade_ios_version
